// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZaLQgW5eNbHfQCfr3-qx8hNJ2ibePwU',
    appId: '1:1041332183554:web:c6022c44527d85bfe23d1b',
    messagingSenderId: '1041332183554',
    projectId: 'electionsamiti',
    authDomain: 'electionsamiti.firebaseapp.com',
    storageBucket: 'electionsamiti.firebasestorage.app',
    measurementId: 'G-3FTP3Y1WKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqg02_8Ca11HlfkL9BtLsBnulDwSSv3Y',
    appId: '1:1041332183554:android:72e007e673134f6fe23d1b',
    messagingSenderId: '1041332183554',
    projectId: 'electionsamiti',
    storageBucket: 'electionsamiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_Rk6K0CuijD5ZJhH_zxs5nOvkmY-zw4',
    appId: '1:1041332183554:ios:c8db6b441311377fe23d1b',
    messagingSenderId: '1041332183554',
    projectId: 'electionsamiti',
    storageBucket: 'electionsamiti.firebasestorage.app',
    iosBundleId: 'com.example.electionSamiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1_Rk6K0CuijD5ZJhH_zxs5nOvkmY-zw4',
    appId: '1:1041332183554:ios:c8db6b441311377fe23d1b',
    messagingSenderId: '1041332183554',
    projectId: 'electionsamiti',
    storageBucket: 'electionsamiti.firebasestorage.app',
    iosBundleId: 'com.example.electionSamiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZaLQgW5eNbHfQCfr3-qx8hNJ2ibePwU',
    appId: '1:1041332183554:web:1eea612a28d30e8fe23d1b',
    messagingSenderId: '1041332183554',
    projectId: 'electionsamiti',
    authDomain: 'electionsamiti.firebaseapp.com',
    storageBucket: 'electionsamiti.firebasestorage.app',
    measurementId: 'G-CBYQTXY7CS',
  );
}
